# This assumes you have mqtt (mosquitto) set up.
# Add to homeassistant configuration:
fan:
  - platform: mqtt
    name: 'buva_fan'
    command_topic: "home/fan"
    speed_command_topic: "home/fan/speed"
    state_topic: 'home/fan'
    speed_state_topic: 'home/fan/speed'

    speeds:
      - "off"
      - low
      - medium
      - high

